aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v1-dependencies-{{ .Branch }}-

  - &install
    run: yarn --no-progress

  - &save-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &cypress-dependencies-install
    run:
      name: Install Cypress dependencies
      command: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

version: 2
jobs:
  Typecheck:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore-cache: *restore-cache
      - *install
      - run: yarn typecheck

  Build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore-cache: *restore-cache
      - *install
      - run: yarn build
      - run: npx bundlesize
      - save-cache: *save-cache

  Test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore-cache: *restore-cache
      - *install
      - run:
          command: yarn test --ci --runInBand
      - store_test_results:
          path: reports

  Semantic Release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - *install
      - run: npx semantic-release

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  Build and Deploy:
    jobs:
      - Typecheck
      - Build
      - Test
      - Semantic Release:
          requires:
            - Typecheck
            - Build
            - Test
          filters:
            branches:
              only:
                - master
